name: cp-vton
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5
#  - cuda75=1.0
#  - cuda90=1.0
  - cudatoolkit=9.0
  #- cudnn=7.3.1=cuda9.0_0
  - freetype=2.9.1
  - intel-openmp=2019.3=199
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
#  - libgcc-ng=8.2.0
#  - libgfortran-ng=7.3.0
  - libpng=1.6.37
#  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
#  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.15.2
  - numpy-base=1.15.2
  - olefile=0.46=py35_0
  - openssl=1.0.2r
  - pillow=5.2.0
  - pip=10.0.1
  - pycparser=2.19
  - python=3.5.6
  - pytorch=0.4.1
  - readline=7.0
  - setuptools=40.2.0=py35_0
  - six=1.11.0=py35_1
  - sqlite=3.28.0
  - tk=8.6.8
  - torchvision=0.2.1=py_2
  - wheel=0.31.1=py35_0
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - bleach==1.5.0
    - chardet==3.0.4
    - cython==0.29.8
    - grpcio==1.21.1
    - html5lib==0.9999999
    - idna==2.8
    - markdown==3.1.1
    - protobuf==3.7.1
    - pyyaml==5.1
    - requests==2.22.0
    - tensorboard==1.6.0
    - tensorboard-pytorch==0.7.1
    - tensorboardx==1.1
    - urllib3==1.25.3
    - werkzeug==0.15.4
